name: 'Tag with npm version'
description: 'Tag the git repo with package.json version'
author: 'YieldRay'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  origin:
    description: 'Remote origin'
    required: false
    default: 'origin'

# Define your outputs here.
outputs:
  version:
    description: 'Version of package.json'
  skip:
    description: 'If tag already exists'

runs:
  using: node20
  main: dist/index.js
