name: 'Tag with npm version'
description: 'Tag the git repo with package.json version'
author: 'YieldRay'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  origin:
    description: 'Remote origin'
    required: false
    default: 'origin'
  prefix:
    description: 'Prefix string of the tag'
    required: false
    default: ''
  force:
    description: 'Force push'
    required: false
    default: 'false'
  dir:
    description: 'Directory of the package.json'
    required: false
    default: '.'

# Define your outputs here.
outputs:
  version:
    description: 'Version of package.json'
  skip:
    description: 'If not force push and tag already exists'

runs:
  using: node20
  main: dist/index.js
